// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kern_reg
SEXP kern_reg(const SEXP xnew, const SEXP y, const SEXP x, const NumericVector h, std::string type, int ncores);
RcppExport SEXP _kernreg_kern_reg(SEXP xnewSEXP, SEXP ySEXP, SEXP xSEXP, SEXP hSEXP, SEXP typeSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type xnew(xnewSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< const SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(kern_reg(xnew, y, x, h, type, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kernreg_kern_reg", (DL_FUNC) &_kernreg_kern_reg, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_kernreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
