# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kern_reg <- function(xnew, y, x, h = as.numeric( c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0 )), type = "gauss", ncores = 1L) {
    .Call(`_kernreg_kern_reg`, xnew, y, x, h, type, ncores)
}

